### ISSUE TITLE
Request for basic documentation

### ISSUE THREAD

**Issue by trholding** [lucidrains/muse-pytorch#3]
Thank you for the quick implementation of the Muse code. A bit of documentation / a quick howto would be highly appreciated.

Particularly a howto on this:

- How to train the model(s)
- How to do inference / generate images

**Comment by trholding** [comment]
Oh sorry. Closing this. Saw that it is not done yet.

**Comment by lucidrains** [comment]
patience, the paper just got released two days ago.

**Comment by lucidrains** [comment]
@trholding ok, it has been added

will add some trainers on sunday
